export default function AboutPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-12">
      <div className="animate-fade-in-up">
        <h1
          className="text-gradient text-3xl font-bold"
          style={{ fontFamily: 'Outfit, sans-serif' }}
        >
          About StreamOracle
        </h1>
        <p className="mt-3 text-gray-400">
          Transparent, multi-platform viewership analysis.
        </p>
      </div>

      {/* Mission */}
      <section className="mt-12 animate-fade-in-up" style={{ animationDelay: '0.1s' }}>
        <h2
          className="text-xl font-semibold text-gray-100"
          style={{ fontFamily: 'Outfit, sans-serif' }}
        >
          Mission
        </h2>
        <div className="glass-card mt-4 border-l-2 border-l-violet-500/40 p-6">
          <p className="text-sm leading-relaxed text-gray-300">
            StreamOracle exists to bring transparency to live streaming viewership
            data. By collecting and analyzing viewer metrics across multiple platforms,
            we aim to provide the community with objective, data-driven insights into
            viewership patterns. Our goal is not to accuse anyone of wrongdoing, but
            to provide tools for informed analysis.
          </p>
        </div>
      </section>

      {/* Open Source */}
      <section className="mt-10 animate-fade-in-up" style={{ animationDelay: '0.15s' }}>
        <h2
          className="text-xl font-semibold text-gray-100"
          style={{ fontFamily: 'Outfit, sans-serif' }}
        >
          Open Source
        </h2>
        <div className="glass-card mt-4 border-l-2 border-l-cyan-500/40 p-6">
          <p className="text-sm leading-relaxed text-gray-300">
            StreamOracle is fully open source. Every algorithm, every weight, every
            threshold is visible in the codebase. We believe that transparency in our
            methods is essential for trust. Anyone can audit the code, propose
            improvements, or run their own instance.
          </p>
          <a
            href="https://github.com/psxio/streamoracle"
            target="_blank"
            rel="noopener noreferrer"
            className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-cyan-400 transition-colors hover:text-cyan-300"
          >
            <svg className="h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
            </svg>
            View on GitHub
          </a>
        </div>
      </section>

      {/* Disclaimer */}
      <section className="mt-10 animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
        <h2
          className="text-xl font-semibold text-gray-100"
          style={{ fontFamily: 'Outfit, sans-serif' }}
        >
          Disclaimer
        </h2>
        <div className="glass-card mt-4 border-l-2 border-l-amber-500/40 p-6">
          <div className="mb-3 flex items-center gap-2 text-amber-400">
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
            <span className="text-xs font-medium uppercase tracking-wider">Disclaimer</span>
          </div>
          <p className="text-sm leading-relaxed text-gray-300">
            Suspicion scores generated by StreamOracle are statistical indicators
            based on data patterns. They are <strong className="text-gray-100">not</strong> accusations of
            viewership manipulation. Many legitimate factors can produce elevated
            scores, including but not limited to: raids, embeds, platform promotions,
            viral moments, and special events. Users should always consider broader
            context when interpreting results.
          </p>
        </div>
      </section>

      {/* Tech Stack */}
      <section className="mt-10 animate-fade-in-up" style={{ animationDelay: '0.25s' }}>
        <h2
          className="text-xl font-semibold text-gray-100"
          style={{ fontFamily: 'Outfit, sans-serif' }}
        >
          Tech Stack
        </h2>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <div className="glass-card-hover border-t-2 border-t-cyan-500/40 p-5">
            <h3 className="text-sm font-semibold text-gray-200" style={{ fontFamily: 'Outfit, sans-serif' }}>
              Frontend
            </h3>
            <ul className="mt-2 space-y-1 text-sm text-gray-400">
              <li>Next.js 14 (React)</li>
              <li>TypeScript</li>
              <li>Tailwind CSS</li>
              <li>Recharts</li>
            </ul>
          </div>
          <div className="glass-card-hover border-t-2 border-t-violet-500/40 p-5">
            <h3 className="text-sm font-semibold text-gray-200" style={{ fontFamily: 'Outfit, sans-serif' }}>
              Backend
            </h3>
            <ul className="mt-2 space-y-1 text-sm text-gray-400">
              <li>FastAPI (Python)</li>
              <li>SQLite + aiosqlite</li>
              <li>APScheduler</li>
              <li>httpx</li>
            </ul>
          </div>
          <div className="glass-card-hover border-t-2 border-t-amber-500/40 p-5">
            <h3 className="text-sm font-semibold text-gray-200" style={{ fontFamily: 'Outfit, sans-serif' }}>
              Infrastructure
            </h3>
            <ul className="mt-2 space-y-1 text-sm text-gray-400">
              <li>Docker &amp; Docker Compose</li>
              <li>Standalone deployment</li>
            </ul>
          </div>
          <div className="glass-card-hover border-t-2 border-t-cyan-500/40 p-5">
            <h3 className="text-sm font-semibold text-gray-200" style={{ fontFamily: 'Outfit, sans-serif' }}>
              Analysis
            </h3>
            <ul className="mt-2 space-y-1 text-sm text-gray-400">
              <li>7 independent detection signals</li>
              <li>Weighted confidence scoring</li>
              <li>Multi-platform support</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Contributing */}
      <section className="mb-8 mt-10 animate-fade-in-up" style={{ animationDelay: '0.3s' }}>
        <h2
          className="text-xl font-semibold text-gray-100"
          style={{ fontFamily: 'Outfit, sans-serif' }}
        >
          Contributing
        </h2>
        <div className="glass-card mt-4 border-l-2 border-l-cyan-500/40 p-6">
          <p className="text-sm leading-relaxed text-gray-300">
            Contributions are welcome. Whether it&apos;s improving detection algorithms,
            adding platform support, fixing bugs, or enhancing the UI, your help makes
            StreamOracle better for everyone.
          </p>
          <p className="mt-3 text-sm text-gray-500">
            Check the GitHub repository for open issues and contribution guidelines.
          </p>
        </div>
      </section>
    </div>
  );
}
